// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvPzQawnnUeW6Urx8LiQg72KyZZLAjHks',
    appId: '1:1099158978905:web:4b2031b30dfa815e798c48',
    messagingSenderId: '1099158978905',
    projectId: 'onlineldanchool',
    authDomain: 'onlineldanchool.firebaseapp.com',
    storageBucket: 'onlineldanchool.firebasestorage.app',
    measurementId: 'G-FXHMQEXBBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlCPFGRKLYwmTEaksrWsk_Jqxu6Mhu-vM',
    appId: '1:1099158978905:android:ba9c6e4d09501b09798c48',
    messagingSenderId: '1099158978905',
    projectId: 'onlineldanchool',
    storageBucket: 'onlineldanchool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeEQCwOG4YtIehzDik4eboQlj_gtJaNfo',
    appId: '1:1099158978905:ios:dfeac4da0ed4788c798c48',
    messagingSenderId: '1099158978905',
    projectId: 'onlineldanchool',
    storageBucket: 'onlineldanchool.firebasestorage.app',
    androidClientId: '1099158978905-do96cistietvbp7odbh9ksa4pjjk6s1f.apps.googleusercontent.com',
    iosClientId: '1099158978905-c4629kseqta954giumcf1vrm2kpcvsd8.apps.googleusercontent.com',
    iosBundleId: 'com.anexon.noor',
  );
}
